export const LAB_DATA_RECEIVED  = "LAB_DATA_RECEIVED";
export const LAB_DATA_REQUESTED = "LAB_DATA_REQUESTED";
export const PLAN_DATA_RECEIVED  = "PLAN_DATA_RECEIVED";
export const PLAN_DATA_REQUESTED = "PLAN_DATA_REQUESTED";